
mySQL:

CREATE TABLE Events (
	EventID INT NOT NULL AUTO_INCREMENT,
	EventName VARCHAR(55) NOT NULL,
	CreatorUsername VARCHAR(55) NOT NULL,
	EventDate DATE NOT NULL,
	Collaborators TEXT(6400),
	EventDesc TEXT(6400),
	PRIMARY KEY (EventID)
);

CREATE TABLE Users (
	UserID INT(20) NOT NULL AUTO_INCREMENT,
	Username VARCHAR(55) NOT NULL,
	Email VARCHAR(155) NOT NULL,
	Password VARCHAR(155) NOT NULL,
	PRIMARY KEY (`UserID`)
);

POSTGRES vers:

CREATE SEQUENCE Events_seq;

CREATE TABLE Events (
	EventID INT NOT NULL DEFAULT NEXTVAL ('Events_seq'),
	EventName VARCHAR(55) NOT NULL,
	CreatorUsername VARCHAR(55) NOT NULL,
	EventDate DATE NOT NULL,
	Collaborators TEXT,
	EventDesc TEXT,
	PRIMARY KEY (EventID)
);

-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE SEQUENCE Users_seq;

CREATE TABLE Users (
	UserID INT NOT NULL DEFAULT NEXTVAL ('Users_seq'),
	Username VARCHAR(55) NOT NULL,
	Email VARCHAR(155) NOT NULL,
	Password VARCHAR(155) NOT NULL,
	PRIMARY KEY (UserID)
);